config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "static_pages/home" , as: "home_page"
    get "static_pages/help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships,only: %i(create destroy)
  end
end

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div id="error_explanation">
    <% case %>
      <% when flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <% when flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% when flash[:error] %>
        <div class="alert alert-warning">
          <%= flash[:error] %>
        </div>
      <% when flash[:info] %>
        <div class="alert alert-dark">
          <%= flash[:info] %>
        </div>
    <% end %>

  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("name_page"),"#", id:"logo" %>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to t("english"), locale: :en %></li>
        <li><%= link_to t("vietnamese"), locale: :vi %></li>
        <li><%= link_to t("home"),"#" %></li>
        <li><%= link_to t("product"),"#" %></li>
        <li><%= link_to t("user"), users_path %></li>
        <li><%= link_to t("demo"),"#" %></li>
        <li><%= link_to t("microposts.name"),"/vi/static_pages/home" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle" ,"data-toggle": "dropdown", id: "account" do %>
              <%= t("headers.account") %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu" >
              <li><%= link_to t("headers.profile"), current_user %></li>
              <li><%= link_to t("headers.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("headers.log_out"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("sessions.log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>